### ISSUE TITLE
Add YML serialization/deserialization

### ISSUE THREAD

**Issue by andrewbwm** [mal-lang/mal-toolbox#18]
Add YML serialization and deserialization functions for the instance model, attack graph, and language graph.

YML is more light weight than JSON and might be easier to write by hand. Also, Akash, who is working on the GUI interface, is already using YML for his interfaces.

We should probably keep the old JSON functions just for backwards compatibility.

**Comment by nkakouros** [comment]
The good thing with yaml is that it is a superset of json and you can load a json version of the yaml file without issue with the same code. Adding support for Literal values (from the json schema objects module) to the default dumper is enough to have serialization/deserialization support:

https://github.com/mal-lang/mal-toolbox/blob/48ef0fed6acf4d30b9ab6300822b788bc8b6cad3/maltoolbox/model.py#L346-L350
