### ISSUE TITLE
Attack step "firstSteps" is missing an asset

### ISSUE THREAD

**Issue by kasanari** [mal-lang/mal-toolbox#2]
Not sure if this is intended, but should not everything belong to something? 

Is the asset field optional?

**Comment by andrewbwm** [comment]
It is optional but highly recommended. There are two reasons it is optional:
1. If you load an attack graph from a file you may not have the instance model from which it was generated. This will not be the case for most of our work where we generate the attack graph out of instance model.
2. What you have identified, the Attacker is not really an asset of the language, and as such its attack graph node doesn't have an asset associated with it. We could change this, but it would be contrived, MAL languages do not have Attacker assets.

Was this a curiosity or did you actually need the asset for a reason? If it's the former feel free to close this issue.

**Comment by kasanari** [comment]
Alright, then I know.
