### ISSUE TITLE
JSON issue when saving and loading dicts where keys are integers

### ISSUE THREAD

**Issue by mrkickling** [mal-lang/mal-toolbox#75]
Bug:
- JSON Keys can only be strings
- When saving and then loading json, we might see a problem because the keys in some dicts are expected to be integers (entry_points, reached_attack_steps, children of nodes).
- Right now only bug I saw was that some error statements did not manage to print the error msg because it is specified as %d in the format log/msg but it is in fact %s (leads to crash) 

Dig deeper and fix bug.

**Comment by mrkickling** [comment]
I believe it was just a bug where we printed node_id as %d without first converting to int. This is now fixed and branch can be merged.

**Comment by andrewbwm** [comment]
I think the general solution should just be to convert string integers to integers in the _from_dict method.
